### PR TITLE
Updated to zsv 0.3.6.fdcd18e

### PR DESCRIPTION
**Pull request by thareh**

### CODE REVIEW

**Comment by GWRon** [comment]
Thanks for the efforts.

Is there any specific reason to update to "minor-release" revision? Any issues you experienced with the previous rev?

**Comment by thareh** [comment]
No issues with previous revision, just want to keep it up-to-date.

Tried a couple of my programs that uses this zsv and they seem to be functioning correctly after the update.

**Comment by GWRon** [comment]
when doing such things you should not "taint" your "master branch".

For each "planned Pull Request" you create a branch ...

feat_updatezsv
feat_updatemxml
...
in each of them you do the changes required to update the lib etc.
Then you can easily create PR for each of the branches.

And if Brucey rejects your PR (maybe as he simultaneously did the same...) you can simply remove that one branch.

After he merged your PR you can then delete the no longer required "feat_xxxx" branch in your repo. Everything stays clean then - nothing "tainted".

**Comment by thareh** [comment]
Thanks @GWRon. I'm quite the newbie when it comes to GitHub :P

**Review by woollybah — APPROVED** [review]

**Pull request merged**
