### PR TITLE
Text.CharsetDetect. Initial Import.

### PR DESCRIPTION
**Pull request by thareh**
Good day,

Not sure how to go about this, so please bear with me.

I successfully (from the looks of it) wrapped **libchardet** (https://github.com/Joungkyun/libchardet).

I'm not sure if this is at all interesting for BMX-NG, or if I have missed something when it comes to licensing, or missed something code wise, or if it doesn't work for anything other than Windows.

So please let me know if there's any issues so I can learn.

Thanks!

### CODE REVIEW

**Comment by GWRon** [comment]
It compiles fine here on my Mint 22 (GCC11) box.
Example runs through too.
```
Executing:example
utf16_be_bom.txt
Encoding: UTF-16BE
Confidence: 1.00000000
BOM: 1

utf8_bom.txt
Encoding: UTF-8
Confidence: 1.00000000
BOM: 1

utf8.txt
Encoding: UTF-8
Confidence: 0.876250029
BOM: 0

utf16_le_bom.txt
Encoding: UTF-16LE
Confidence: 1.00000000
BOM: 1

ansi.txt
Encoding: windows-1256
Confidence: 0.347905189
BOM: 0
```


What I stumbled over is this:
```
	Rem
	bbdoc: Returns true if the encoding uses BOM (Byte Order Mark) to signal the encoding used
	EndRem
	Method GetBOM:Short()
		Return bmx_chardet_bom(obj)
	EndMethod
```
So returning a `short` for the `True/False` result. It of course works as it should - and it simply returns what the lib uses to return (it uses "short" there too).
Just looks a bit uncommon to have it `:short` and not `:int`.

But I more or less did not stumble over the `short` but the `GetBOM()` as if you would get the Byte Order Mark sequence.
You surely know that different UTF-XX versions have different byte sequences.
(read more about it - https://en.wikipedia.org/wiki/Byte_order_mark)

The "bom" indicator in the lib is either 0 or 1 - so it is just saying "passed file has a BOM sequence at the beginning".

This is why I suggest to rename `Method GetBOM:Short()` to `Method HasBOM:Short()` - which in my opinion is a better wording for an "BOM exists"-indicator.


Despite of that ... good job! well done! and (in my opinion) a perfect imitation of @woollybah 's coding style :)

**Comment by GWRon** [comment]
I asked your example.bmx to identify the test-files in encoding.mod too ..
Interesting that it identifies `iso_8859_8_encoded.txt` as `ISO-8859-9` but fails for the real `iso_8859_8_encoded.txt` ... which module is wrong? :D

|File | Encoding | Confidence | BOM |
| --- | --- | --- | --- |
| ansi.txt | windows-1256 | 0.347905189 | 0 |
| utf16_be_bom.txt | UTF-16BE | 1.00000000 | 1 |
| utf16_le_bom.txt | UTF-16LE | 1.00000000 | 1 |
| utf8_bom.txt | UTF-8 | 1.00000000 | 1 |
| utf8.txt | UTF-8 | 0.876250029 | 0 |
| --- | --- | --- | --- |
| iso_8859_15_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_15_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_1_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_1_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_2_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_2_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_5_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_5_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_6_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_6_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_7_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_7_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_8_encoded.txt | ISO-8859-9 | 0.990000010 | 0 |
| iso_8859_8_utf8.txt | UTF-8 | 0.990000010 | 0 |
| iso_8859_9_encoded.txt |  | 0.00000000 | 0 |
| iso_8859_9_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1250_encoded.txt |  | 0.00000000 | 0 |
| windows_1250_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1251_encoded.txt |  | 0.00000000 | 0 |
| windows_1251_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1252_encoded.txt |  | 0.00000000 | 0 |
| windows_1252_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1253_encoded.txt |  | 0.00000000 | 0 |
| windows_1253_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1254_encoded.txt |  | 0.00000000 | 0 |
| windows_1254_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1255_encoded.txt |  | 0.00000000 | 0 |
| windows_1255_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1256_encoded.txt |  | 0.00000000 | 0 |
| windows_1256_utf8.txt | UTF-8 | 0.990000010 | 0 |
| windows_1257_encoded.txt |  | 0.00000000 | 0 |
| windows_1257_utf8.txt | UTF-8 | 0.990000010 | 0 |

**Comment by thareh** [comment]
"Feels" like it should be able to guess the encoding on more of them, atleast with low confidence. I'll do some experimenting ^^

**Comment by woollybah** [comment]
As for licensing, I'd probably go with MPL, as per the library.

We usually have something like this in the module file too..
```
ModuleInfo "Version: 1.00"
ModuleInfo "Author: libchardet - JoungKyun.Kim"
ModuleInfo "License: MPL"
ModuleInfo "Copyright: libchardet - 2019 JoungKyun.Kim"
ModuleInfo "Copyright: Wrapper - 2024 Carl Arwed Husberg"

ModuleInfo "History: 1.00"
ModuleInfo "History: Initial Release. (libchardet 1.0.6)"
```

**Comment by GWRon** [comment]
> "Feels" like it should be able to guess the encoding on more of them, atleast with low confidence. I'll do some experimenting ^^

Were the experiments fruitful?
Seeing the issue there h***s://git***.com/Joungkyun/libchardet/issues/20 (trying to avoid linking this PR to the github issue) it seems as there is just the "plan" to do so (the lib is not updated since 3 years - so seems it won't get added by the author)

**Comment by thareh** [comment]
Cheers. Added the module info.

Regarding not detecting the Windows* encodings, I think it's more or less impossible to do - Notepad++ just defaults to ANSI on all of them so this module is perhaps more about seeing if the data is UTF8, UTF16 or other.

**Comment by GWRon** [comment]
As said the lib has not been updated since 3 yrs.
https://github.com/nexos-dev/libchardet
This is a fork of it - which at least contains some changes. Dunno if there is some "interesting" stuff added.

I think the detect_file function is nice - but our "LoadString" should do fine already.

**Comment by thareh** [comment]
Indeed, looks like the project it's based upon in dead as well, but I guess there aren't many new encodings coming out so perhaps no "need" for updates. The fork doesn't really contain any improvements to the detection as far as I can tell, too bad.

**Pull request closed without merging**
